language: node_js
sudo: false
branches:
  except:
    - develop
script: npm run cover
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - stable
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: freeformsystems@gmail.com
  api_key:
    secure: FCNtUE3c7Pbx1JUHEotAkpeJDFT9AQop2DE5JPOPgSWjvhmnknqSzF3/IAd6rBrYMhEYRpiW0dbPxAtQMoZLY8DGy8HniqeWrlINhkM9jQx6z3f3LsKv7iv4bk5+90Bbm7LKpZqGl8uDnz0Df+ddk0OrjZWPOC7SfE3oRaOOMQDgMpRJXrtHAq9ziDb3TfNRp4vxnQ4V4svRXqtzijDELh40xKC2/8UlX+bB1tkQ6A4YJ77KDIMCih2veSgBxIgFgW0PX8z6z6EjH8TU01EVoyGhb60UJrzGpVJA+duu/UkLd+SI6JIHCU4CoK2mmbklOTLPdqBkTCJTTnrCa4JftEptFVFPJMP3EoZ3FaopkMSzP9WETkMxpH6OJYxIjSPQZltun/ggyu0gtCQhj8jTdjEAnck5XD3JyPt6YRzwV3E647H7IQbX9kr/c1EVe0Ezk5E3BjOiQh8t1mIx4951+sBLdEhoYcNZ6GY/1w8vXNiJ+YMOXZeU8tktRcr3I0GrybpKdCIoqjBTZYR9NQF/AUgVtR1hq/ryhyM5IWZasSy9fn0mXFIPKX9XTHSrC8X5ncfGMHcuwAY+6G/FSnPiqV7TA3a4KBYbzylGLzWMw5SZu5eIcNq5Kqz/5O+x4hv4QQagT3t+l/JJkuV82XG/YZW6LZ332GXuqoZ6ynz5ojQ=
  on:
    tags: true
    repo: mkdoc/mkhighlight
    node: '4.1'
